### ISSUE TITLE
Program fails to open

### ISSUE THREAD

**Issue by Kaszanas** [uwburn/cardia#12]
Basically it doesn't matter how I try to open it it fails to do so.
It is the most current version from what I know.

![image](https://user-images.githubusercontent.com/34846245/37243235-7271a966-2476-11e8-9988-52abd56d5bdd.png)

**Comment by uwburn** [comment]
If you are using Windows 7, you should use: [v1.1 Legacy](https://github.com/uwburn/cardia/releases/tag/v1.1_legacy). Please note this version doesn't support BT Smart, as Windows 7 itself doesn't support BT Smart.

**Comment by Kaszanas** [comment]
Then what devices would be supported?

**Comment by Kaszanas** [comment]
I was looking into that idea of HRM while using PC for a while, now I need to test it somehow and later maybe use it.
What is BT smart? I am really currently not heavily into that peripherial devices zone as there's lots of products.

**Comment by uwburn** [comment]
Bluetooth Smart o Bluetooth 4.0 + LE (Low Energy) is a protocol that allows many HRM devices to comunicate with a standrd profile. BT Smart on Windows is supported since 8.1, and if you use Windows 10, you will need to use Falls Creators Update for it to work correctly (basically, you need Windows 10 to be updated to the latest version).

On Windows 7 only specific devices are supported: Zephyr HxM and Contec CMS 50. For further details, see the readme.
