### ISSUE TITLE
Can't Build from Source -- Component 'Windows' Not Found

### ISSUE THREAD

**Issue by vingenuity** [uwburn/cardia#30]
Howdy uwburn,

I cloned this project earlier this evening because I wanted to investigate adding hex color support. However, I've had a heck of a time getting the solution to build.

The base error I'm getting is: "The referenced component 'Windows' could not be found."

From what I can tell, this would be referring to the Windows 10 UWP APIs. I've attempted to install the latest Windows 10 SDK, but that has not resolved the problem.

Could you run me through how you have the references to the Windows namespace set up on your machine, so that I can get it building on my machine?

Thanks!

**Comment by uwburn** [comment]
Hello @vingenuity, sorry, it took me some time to access back the project setup to check this.

The file i'm referencing is `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.15063.0\Windows.winmd`, the path looks like Win 10 specific, but something similar should be there from Win 8 era.

It's been quite a bit of time since i setted up the id (VS2017), so i don't recall correctly all the steps, anyway i'm having istalled the following:

- Windows Software Development Kit - Windows 10.1.15063.468
- Windows Software Development Kit - Windows 10.1.16299.15
- Windows SDK AddOn

Hope this helps.

**Comment by uwburn** [comment]
Stale.
