### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by Ciseur** [uwburn/cardia#6]
Hello Michele,

After searching for a long time your program is the only one doing exactly what I am looking for.
But I have an issue: Couldn't launch it on Windows 10.

It appears adter installing Visual Studio that the problem is due to reference to certain DLL:
System.Runtime
System.Runtime.InteropServices.WindowsRuntime
Windows

I found the good DLL for the 2 firsts in .Net Framework but couldn't find for Windows.
Can you help?

Thanks you very much for your program who is so rare.
Regards,
Simon

**Comment by ghost** [comment]
Same problem, anyone found a solution for pre-release 1 version on Windows 10?

**Comment by uwburn** [comment]
Hello,
i currently don't own a BT smart device to test PR1 (either win 8 or win 10 should be the same). The one i bought was a faulty crap and i'm still on hold. If i get one i can try to sort it out, as i now also have a non-dev machine with win 10 to try it out (i suspect having VisualStudio installed can make it to work while not working otherwise).

**Comment by uwburn** [comment]
I think this was related to Bluetooth device detection that was fixed in BT-Smart-pre.2. I'm closing this down.

**Comment by Ciseur** [comment]
Yes it does! Thanks a lot man! If you want to see the result my Twitch name is Ciseur. I'll for sure recommend this soft!

**Comment by uwburn** [comment]
Are you using a BT Smart device? If so, wich brand it is? Having a feedback about the setup would really be helpful as i'm struggling with BT Smart support, see #3.

**Comment by Ciseur** [comment]
Polar H7
