### ISSUE TITLE
ANT+ Devices

### ISSUE THREAD

**Issue by veanome** [uwburn/cardia#9]
Will this sync up with ANT+ devices? I can't seem to get my Garmin HRM to connect..

Thanks!

**Comment by uwburn** [comment]
No, ANT+ protocol is not supported at the moment.

I never digged about it, i would bet adding support for it is possible, but without having a device to test out i cannot carry on the implementation.

**Comment by veanome** [comment]
I would absolutely believe implementation is possible. ANT+ seems to be a very common protocol for HRM next to BT. Is there anyway we could potentially help you get a device in your hands to work with?

Thanks again for the response, hope all is well!

**Comment by uwburn** [comment]
Well, i was accepting donations for this kind of stuff, but to be entirely honest, at the moment i'm about to move to a new house, so i'm afraid i will be out of spare time for a while. :)

Also, BT Smart was quite a nightmare (mostly due to Windows API oddities), so before taking on a new protocols and ask for donations to buy the equipment to test it, i would take a deep look at it.

When i will look at at it i will report back here... thanks for the interest anyway!

**Comment by veanome** [comment]
Congrats on the move! I just recently did the same thing and it was a busy time..

If you ever do take a look and think it's possible, please come back and let us know! I'm very much willing to help you out anyway I can!

**Comment by invisan** [comment]
@veanome Either way for it to work you need an ANT+ Dongle so you can connect to your Desktop. Golden Cheetah is one Software Capable of connecting so you can get your Heartrate there. Unfortunately GC has no ECG which i find quite Interesting as Feature so i would +1 the Initial Request here.

**Comment by LividJava** [comment]
Bump to this, A lot of more generic devices tend to support ANT+ and is imo better for this kind of thing. and @invisan as far as im aware the ECG in app is merely  just cosmetic

**Comment by hotfistdotcom** [comment]
Ant+ is also much, much less battery intensive than bluetooth. On my chest strap, BT lasts 30-40 hours, ant+ lasts 300-ish hours.

**Comment by sur1v** [comment]
Another big UP for ANT+, if you need a device to test check for a used Garmin Vivosmart 4, they are really cheap on Ebay :) Thanks for this project!
